// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("AR")
                        .HasColumnType("smallint");

                    b.Property<short>("Base")
                        .HasColumnType("smallint");

                    b.Property<short>("CC")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DEF")
                        .HasColumnType("smallint");

                    b.Property<short>("DPCost")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Designation")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<short>("DesignationLimitValue")
                        .HasColumnType("smallint");

                    b.Property<string>("DesignationTypeLimit")
                        .HasColumnType("text");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("FactionAvailabilities")
                        .HasColumnType("text[]");

                    b.Property<short>("LD")
                        .HasColumnType("smallint");

                    b.Property<short>("MV")
                        .HasColumnType("smallint");

                    b.Property<short>("MW")
                        .HasColumnType("smallint");

                    b.Property<short>("PW")
                        .HasColumnType("smallint");

                    b.Property<short>("SPCost")
                        .HasColumnType("smallint");

                    b.Property<short>("ST")
                        .HasColumnType("smallint");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("W")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Domain.Entities.UnitSpecialAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueX")
                        .HasColumnType("text");

                    b.Property<string>("ValueY")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("UnitSpecialAbilities");
                });

            modelBuilder.Entity("Domain.Entities.UnitWeapon", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("UnitId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("UnitWeapons");
                });

            modelBuilder.Entity("Domain.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("CCDam")
                        .HasColumnType("smallint");

                    b.Property<short>("CCMod")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("CritFail")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("LongRange")
                        .HasColumnType("smallint");

                    b.Property<short>("LongRangeDam")
                        .HasColumnType("smallint");

                    b.Property<short>("LongRangeMod")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("ShortRange")
                        .HasColumnType("smallint");

                    b.Property<short>("ShortRangeDam")
                        .HasColumnType("smallint");

                    b.Property<short>("ShortRangeMod")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Domain.Entities.WeaponSpecialAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueX")
                        .HasColumnType("text");

                    b.Property<string>("ValueY")
                        .HasColumnType("text");

                    b.Property<Guid?>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponSpecialAbilities");
                });

            modelBuilder.Entity("Domain.Entities.UnitSpecialAbility", b =>
                {
                    b.HasOne("Domain.Entities.Unit", null)
                        .WithMany("UnitSpecialAbilities")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Domain.Entities.UnitWeapon", b =>
                {
                    b.HasOne("Domain.Entities.Unit", "Unit")
                        .WithMany("UnitWeapon")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Weapon", "Weapon")
                        .WithMany("UnitWeapon")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Domain.Entities.WeaponSpecialAbility", b =>
                {
                    b.HasOne("Domain.Entities.Weapon", null)
                        .WithMany("WeaponSpecialAbilities")
                        .HasForeignKey("WeaponId");
                });

            modelBuilder.Entity("Domain.Entities.Unit", b =>
                {
                    b.Navigation("UnitSpecialAbilities");

                    b.Navigation("UnitWeapon");
                });

            modelBuilder.Entity("Domain.Entities.Weapon", b =>
                {
                    b.Navigation("UnitWeapon");

                    b.Navigation("WeaponSpecialAbilities");
                });
#pragma warning restore 612, 618
        }
    }
}
